### ISSUE TITLE
undefined reference to `sam_index_build' on make

### ISSUE THREAD

**Issue by Beherith** [Mesh89/TranSurVeyor#1]
/TranSurVeyor/cmake-3.12.3-Linux-x86_64/bin/cmake . && make
-- Configuring done
-- Generating done
-- Build files have been written to: /home/[redacted]/TranSurVeyor
[  6%] Linking CXX executable filter
CMakeFiles/filter.dir/filter.cpp.o: In function `open_samFile(char const*, bool)':
filter.cpp:(.text+0x1f3c): undefined reference to `sam_index_build'
collect2: error: ld returned 1 exit status
make[2]: *** [filter] Error 1
make[1]: *** [CMakeFiles/filter.dir/all] Error 2
make: *** [all] Error 2

**Comment by Beherith** [comment]
On another, also ubuntu 16.04 machine, I get the following error on cmake ., after successful compilation of build_htslib script

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
HTS_LIB
    linked by target "filter" in directory /home/speter/oe_pgs/TranSurVeyor
    linked by target "add_filtering_info" in directory /home/speter/oe_pgs/TranSurVeyor
    linked by target "reads_categorizer" in directory /home/speter/oe_pgs/TranSurVeyor
    linked by target "clip_consensus_builder" in directory /home/speter/oe_pgs/TranSurVeyor
    linked by target "sc_categorizer" in directory /home/speter/oe_pgs/TranSurVeyor
    linked by target "dc_remapper" in directory /home/speter/oe_pgs/TranSurVeyor

-- Configuring incomplete, errors occurred!
See also "/home/speter/oe_pgs/TranSurVeyor/CMakeFiles/CMakeOutput.log".

**Comment by Mesh89** [comment]
Hi,

I updated CMakeLists.txt.

Can you try building again from scratch using the new file?

**Comment by Beherith** [comment]
Thanks, it now builds fine on the machine with native cmake.
