### ISSUE TITLE
Error while running surveyor.py

### ISSUE THREAD

**Issue by Nisha-Hemandhar-Kumar** [Mesh89/TranSurVeyor#2]
I have tried to detect the transpositions using the tool TranSurVeyor. However I get an error message as follows,

python surveyor.py sorted.bam outputfiles/ hg19.fa

100000 random positions generated.
200000 random positions generated.
300000 random positions generated.
400000 random positions generated.
500000 random positions generated.
600000 random positions generated.
700000 random positions generated.
800000 random positions generated.
900000 random positions generated.
1000000 random positions generated.
Traceback (most recent call last):
  File "surveyor.py", line 85, in <module>
    for read in bam_file.fetch(contig=chr, start=pos, end=pos+10000):
  File "pysam/libcalignmentfile.pyx", line 1076, in pysam.libcalignmentfile.AlignmentFile.fetch
  File "pysam/libchtslib.pyx", line 686, in pysam.libchtslib.HTSFile.parse_region
ValueError: invalid contig `chr6_apd_hap1`

I have a bam file from Whole exome data which was generated using high throughput sequencing technique illumina.

I would like some help to sort this issue.

Thanks
Nisha Hemandhar

**Comment by Mesh89** [comment]
The reference you give TranSurVeyor should the same one you used to generate the BAM file.
 Solved.
