### ISSUE TITLE
How to install  TranSurVIndel?

### ISSUE THREAD

**Issue by Anticyclone-op** [Mesh89/TranSurVeyor#6]
I encountered an installation problem. It should be caused by the low version of system C, gcc version 4.4.7. TranSurVIndel only recognizes the C of the system, not the C assigned to it or the C of the environment variable, gcc-6.4.0. How should I solve it?

cmake-3.5.2/bin/cmake -DCMAKE_BUILD_TYPE=Release . && make
-- Configuring done
-- Generating done
-- Build files have been written to: SurVIndel-master
[  7%] Building CXX object CMakeFiles/filter.dir/filter.cpp.o
In file included from SurVIndel-master/filter.cpp:6:
SurVIndel-master/cluster.h:5:18: error: atomic: No such file or directory
In file included from SurVIndel-master/config.h:9,
                 from SurVIndel-master/filter.cpp:5:
SurVIndel-master/libs/IntervalTree.h: In constructor ‘IntervalTree<T, K>::IntervalTree()’:
SurVIndel-master/libs/IntervalTree.h:60: error: ‘nullptr’ was not declared in this scope
SurVIndel-master/libs/IntervalTree.h: In copy constructor ‘IntervalTree<T, K>::IntervalTree(const IntervalTree<T, K>&)’:
SurVIndel-master/libs/IntervalTree.h:73: error: ‘nullptr’ was not declared in this scope
SurVIndel-master/libs/IntervalTree.h: In member function ‘IntervalTree<T, K>& IntervalTree<T, K>::operator=(const IntervalTree<T, K>&)’:
SurVIndel-master/libs/IntervalTree.h:84: error: ‘nullptr’ was not declared in this scope
SurVIndel-master/libs/IntervalTree.h: In constructor ‘IntervalTree<T, K>::IntervalTree(std::vector<Interval<T, K>, std::allocator<Interval<T, K> > >&, size_t, size_t, K, K, size_t)’:
SurVIndel-master/libs/IntervalTree.h:98: error: ‘nullptr’ was not declared in this scope
In file included from SurVIndel-master/filter.cpp:5:
SurVIndel-master/config.h: At global scope:
SurVIndel-master/config.h:21: error: ISO C++ forbids initialization of member ‘rmsk_fname’
SurVIndel-master/config.h:21: error: making ‘rmsk_fname’ static
SurVIndel-master/config.h:21: error: invalid in-class initialization of static data member of non-integral type ‘std::string’
SurVIndel-master/config.h:21: error: ISO C++ forbids initialization of member ‘simple_rep_fname’
SurVIndel-master/config.h:21: error: making ‘simple_rep_fname’ static
SurVIndel-master/config.h:21: error: invalid in-class initialization of static data member of non-integral type ‘std::string’
SurVIndel-master/config.h: In function ‘std::unordered_map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, IntervalTree<repeat_t, long unsigned int>*, std::hash<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, IntervalTree<repeat_t, long unsigned int>*> > > parse_repeats(std::string)’:
SurVIndel-master/config.h:80: error: expected initializer before ‘:’ token
SurVIndel-master/config.h:83: error: expected primary-expression before ‘}’ token
SurVIndel-master/config.h:83: error: expected ‘;’ before ‘}’ token
SurVIndel-master/config.h:83: error: expected primary-expression before ‘}’ token
SurVIndel-master/config.h:83: error: expected ‘)’ before ‘}’ token
SurVIndel-master/config.h:83: error: expected primary-expression before ‘}’ token
SurVIndel-master/config.h:83: error: expected ‘;’ before ‘}’ token
SurVIndel-master/config.h: In function ‘std::unordered_map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, IntervalTree<simple_repeat_t, long unsigned int>*, std::hash<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, IntervalTree<simple_repeat_t, long unsigned int>*> > > parse_simple_repeats(std::string, int)’:
SurVIndel-master/config.h:104: error: expected initializer before ‘:’ token
SurVIndel-master/config.h:107: error: expected primary-expression before ‘}’ token
SurVIndel-master/config.h:107: error: expected ‘;’ before ‘}’ token
SurVIndel-master/config.h:107: error: expected primary-expression before ‘}’ token
SurVIndel-master/config.h:107: error: expected ‘)’ before ‘}’ token
SurVIndel-master/config.h:107: error: expected primary-expression before ‘}’ token
SurVIndel-master/config.h:107: error: expected ‘;’ before ‘}’ token
SurVIndel-master/config.h: In function ‘config_t parse_config(std::string)’:
SurVIndel-master/config.h:123: error: ‘struct config_t’ has no member named ‘rmsk_fname’
SurVIndel-master/config.h:126: error: ‘struct config_t’ has no member named ‘simple_rep_fname’
In file included from SurVIndel-master/cluster.h:7,
                 from SurVIndel-master/filter.cpp:6:
SurVIndel-master/sam_utils.h: At global scope:
SurVIndel-master/sam_utils.h:23: error: ISO C++ forbids initialization of member ‘n_types’
SurVIndel-master/sam_utils.h:23: error: making ‘n_types’ static
SurVIndel-master/sam_utils.h:23: error: ISO C++ forbids in-class initialization of non-const static member ‘n_types’
SurVIndel-master/sam_utils.h: In function ‘bool check_SNP(bam1_t*, std::deque<bam1_t*, std::allocator<bam1_t*> >&, double)’:
SurVIndel-master/sam_utils.h:201: error: expected initializer before ‘:’ token
SurVIndel-master/filter.cpp:169: error: expected primary-expression at end of input
SurVIndel-master/filter.cpp:169: error: expected ‘;’ at end of input
SurVIndel-master/filter.cpp:169: error: expected primary-expression at end of input
SurVIndel-master/filter.cpp:169: error: expected ‘)’ at end of input
SurVIndel-master/filter.cpp:169: error: expected statement at end of input
SurVIndel-master/filter.cpp:169: error: expected ‘}’ at end of input
make[2]: *** [CMakeFiles/filter.dir/filter.cpp.o] Error 1
make[1]: *** [CMakeFiles/filter.dir/all] Error 2
make: *** [all] Error 2

**Comment by Mesh89** [comment]
Hi,

As you suspected, you need a more recent version of GCC in order to build TranSurVeyor.

I am not sure what you mean by "TranSurVIndel only recognizes the C of the system, not the C assigned to it or the C of the environment variable". CMake is performing the building process, and you have to specify if you want to use a different GCC from the system one.
There are different ways to do so, you may want to look into the variable DCMAKE_CXX_COMPILER, for example.

Finally, it seems to me that you are trying to build SurVIndel, not TranSurVeyor, although the building process is essentially the same.

**Comment by Anticyclone-op** [comment]
Sorry, I am installing these two software at the same time, and I confuse the error message.

Thank you very much. Specify gcc and g++ with -DCMAKE_C_COMPILER and -DCMAKE_CXX_COMPILER, and the installation is successful.
